import { useState } from 'react';
import './customDropdown.css'; // Import CSS for styling

export interface CustomDropDownProps {
    options: string[]
    onSelect: (option: string) => void
}
// This component was generated by chat gpt inclding the styling used
export default function CustomDropdown({ options, onSelect }: CustomDropDownProps)
{
  const [isOpen, setIsOpen] = useState(false);
  const [selectedOption, setSelectedOption] = useState(options[0]);

  const handleToggle = () => {
    setIsOpen(!isOpen);
  };

  const handleOptionSelect = (option: string) => {
    setSelectedOption(option);
    onSelect(option);
    setIsOpen(false);
  };

  return (
    <div className="custom-dropdown">
      <button className="dropdown-toggle" onClick={handleToggle}>
        {selectedOption} <span className={`dropdown-icon ${isOpen ? 'open' : ''}`}>&#9662;</span>
      </button>
      {isOpen && (
        <ul className="dropdown-options">
          {options.map((option, index) => (
            <li key={index} onClick={() => handleOptionSelect(option)}>{option}</li>
          ))}
        </ul>
      )}
    </div>
  );
};
